[package]
name = "oyente"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.104"
block2 = "0.6.2"
core-graphics = "0.25.0"
cpal = "0.18.2"
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-foundation = { version = "0.3.2", features = ["NSTimer", "NSDate", "block2"] }
parakeet-rs = "0.3.7"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.5"
tray-icon = "0.24.2"

[profile.release]
opt-level = 3
